version: '3'

services:
  test_app:
    build:
      context: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "80:80"
    depends_on:
      - test_pg
    networks:
      - test_network

  test_pg:
    build:
      context: ./db
    environment:
      - POSTGRES_USER=userpg
      - POSTGRES_PASSWORD=pwd1234
      - POSTGRES_DB=test
      - POSTGRES_HOST_AUTH_METHOD=md5
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - test_network

networks:
  test_network:

volumes:
  postgres_data:
